#!/bin/sh
#set -x
#
# smokeping    This starts and stops the smokeping daemon
# chkconfig: 345 98 11
# description: Start/Stop the smokeping daemon
# processname: smokeping
# Source function library.
#. /etc/rc.d/init.d/functions
. /etc/init.d/functions

SMOKEPING=/opt/smokeping/bin/smokeping
LOCKF=/var/lock/subsys/smokeping
CONFIG=/opt/smokeping/etc/config
smokeping_options="--logfile=/var/log/smokeping.log"

[ -f $SMOKEPING ] || exit 0
[ -f $CONFIG ] || exit 0

RETVAL=0

case "$1" in
  start)
        #/opt/smokeping/bin/smokeping-service-notification.sh start
        chown -R root:apache /opt/smokeping/cache
        chmod -R 775 /opt/smokeping/cache
        chown -R root:apache /opt/smokeping/data
        chmod -R 775 /opt/smokeping/data
        echo -n $"Starting SMOKEPING: "
        daemon $SMOKEPING $smokeping_options
        RETVAL=$?
        service httpd restart
        /opt/smokeping/bin/start-slaves
        echo
        [ $RETVAL -eq 0 ] && touch $LOCKF
        ;;
  stop)
        #/opt/smokeping/bin/smokeping-service-notification.sh stop
        chown -R root:apache /opt/smokeping/cache
        chmod -R g+rwx /opt/smokeping/cache
        chown -R root:apache /opt/smokeping/data
        chmod -R g+rwx /opt/smokeping/data
        echo -n $"Stopping SMOKEPING: "
        killproc $SMOKEPING
        RETVAL=$?
        /opt/smokeping/bin/stop-slaves
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCKF
        ;;
  status)
        status smokeping
        RETVAL=$?
        ;;
  reload)
        chown -R root:apache /opt/smokeping/cache
        chmod -R g+rwx /opt/smokeping/cache
        chown -R root:apache /opt/smokeping/data
        chmod -R g+rwx /opt/smokeping/data
        echo -n $"Reloading SMOKEPING: "
        killproc $SMOKEPING -HUP
        RETVAL=$?
        echo
        ;;
  restart)
        #/opt/smokeping/bin/smokeping-service-notification.sh restart
        chown -R root:apache /opt/smokeping/cache
        chmod -R g+rwx /opt/smokeping/cache
        chown -R root:apache /opt/smokeping/data
        chmod -R g+rwx /opt/smokeping/data
        $0 stop
        sleep 3
        $0 start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f $LOCKF ]; then
                $0 stop
                sleep 3
                $0 start
                RETVAL=$?
        fi
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
        exit 1
esac

exit $RETVAL
